Django Projects/restroworks/orders/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # path("metrics", views.order_metrics, name="order_metrics"),
    path("create", views.create_order, name="create_order"),
    path(
        "view/<int:pk>",
        login_required(views.OrderDetailView.as_view()),
        name="retrieve_order",
    ),
    # path("view/<int:order_id>", views.retrieve_order, name="retrieve_order"),
    # path("view/all", views.list_orders, name="list_orders"),
    path("view/all", login_required(views.OrderListView.as_view()), name="list_orders"),
    path("view/active", views.list_active_orders, name="list_active_orders"),
    path(
        "view/status/<int:order_id>",
        views.track_order_status,
        name="track_order_status",
    ),
    # path(
    #     "view/all/customer",
    #     views.retrieve_all_customer_orders,
    #     name="retrieve_all_customer_orders",
    # ),
    path(
        "view/all/customer",
        views.CustomerOrderListView.as_view(),
        name="retrieve_all_customer_orders",
    ),
    path(
        "update/<int:order_id>",
        login_required(views.MenuItemFormView.as_view()),
        name="update_order",
    ),
    # path("update/<int:order_id>", views.update_order, name="update_order"),
    path("cancel/<int:order_id>", views.cancel_order, name="cancel_order"),
    path("delete/<int:order_id>", views.delete_order, name="delete_order"),
]

Django Projects/restroworks/orders/models.py
from django.db import models
from customers.models import Customer
from menu.models import MenuItem

# Better to use numbers instead of 'C, IK, D' to improve query performance.
STATUS_CHOICES = (
    (1, "Confirmed"),
    (2, "In Kitchen"),
    (3, "Delivered"),
    (4, "Cancelled"),
)


# related_name is an attribute that can be used to specify the name of the reverse relation from the related model back to the model that defines the relation - in simple terms if PK of A acts as FK in B and and B defines related name 'abc' for A, A can refer to B, i.e. reverse relation, using related name 'abc'.
# Customer can refer to Order using related_name 'orders'.
class Order(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.CASCADE, related_name="orders"
    )
    status = models.IntegerField(choices=STATUS_CHOICES, default=1)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def calculate_total(self):
        self.total_price = sum(item.total_price() for item in self.items.all())
        self.save()


# Order can refer to OrderItem using related_name 'items'.
class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="items")
    menu_item = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    def total_price(self):
        return self.quantity * self.price

    def __str__(self):
        return f"{self.menu_item.name} ({self.quantity})"


# Flow: Create Order object -> Create all related OrderItem objects (price is updated on save()) -> Update Order.total_price using calculate_total().

Django Projects/restroworks/orders/templates/order_details.html
{% extends "base.html" %}
{% block content %}
<div class='heading'>
    <h4>Order Details</h4>
</div>
<div class='subheading'>
    <h5>Item Summary</h5>
</div>
<div class="order-details">
    <div class="overview">
        <h5>Order ID: {{ order.id }}</h5>
        {% if user.is_staff %}
        <h5>Customer ID: {{ order.customer.id }}</h5>
        <h5>Name: {{ order.customer.user.first_name }} {{ order.customer.user.last_name }}</h5>
        <h5>Phone: {{ order.customer.phone }}</h5>
        <h5>Email: {{ order.customer.email }}</h5>
        {% endif %}
        <h5>Date: {{ order.created_at }}</h5>
        <h5>Total: ₹{{ order.total_price }}</h5>
        <h5>Order Status: {{ order.get_status_display }}</h5>
        {% if user.is_staff %}
        <a href="/orders/update/{{ order.id }}">Edit Order Status</a>
        {% if form %}
        <form class="main-form order-status-form" method="post" autocomplete="off" id="main-form" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="input-box order-status-input">
                <label class="input-label order-status-label" for="id_status"></label>
                <select name="status" id="id_status">
                    <option value="1">Confirmed</option>
                    <option value="2">In Kitchen</option>
                    <option value="3">Delivered</option>
                    <option value="4">Cancelled</option>
                </select>   
                <button type="submit" class="btn-primary clr-1 order-status-button">Update</button>
            </div>
          </form>
        {% endif %}
        {% endif %}
    </div>
    <div class="summary-table-holder">
        <table class="query-table menu-item-table">
            <thead>
                <tr>
                    <th>Item</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Subtotal</th>
                </tr>
            </thead>
            <tbody>
                {% for item in order.items.all %}
                <tr>
                    <td class="menu-item-name">{{ item.menu_item }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>₹{{ item.price }}</td>
                    <td>₹{{ item.total_price }}</td>       
                </tr>
                {% endfor %}
                <tr>
                    <td><strong>Order Total</strong></td>
                    <td></td>
                    <td></td>
                    <td><strong>₹{{ order.total_price }}</strong></td>       
                </tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

Django Projects/restroworks/orders/templates/order_list.html
{% extends "base.html" %}
{% block content %}
<div class="table-holder">
    <table class="query-table">
        <thead>
            <tr>
                <th>Order ID</th>
                {% if user.is_staff %}<th>Customer ID</th>{% endif %}
                <th>Date</th>
                <th>Items</th>
                <th>Total</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
            <tr>
                <td class="order-id">{{ order.id }}</td>
                {% if user.is_staff %}
                <td class="customer-id">{{ order.customer.id }}</td>
                {% endif %}
                <td class="order-date">{{ order.created_at }}</td>
                <td class="order-items">
                    <div class="item-overview">
                        {% for item in order.items.all %}
                        {{ item.menu_item }} ({{ item.quantity }}){% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </div>
                </td>
                <td class="order-total">₹{{ order.total_price }}</td>
                <td class="order-status">{{ order.get_status_display }}</td>
                <td class="order-actions">
                    <a href="/orders/view/{{ order.id }}" class="order-actions">View Details</a>
                </td>                
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}